projects:
  projectapi:
    schemaPath: graphql/schema.json
    includes:
      - project-graphql-file.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
